### ISSUE TITLE
Is it possible to call a variable number of arguments function through ffi?

### ISSUE THREAD

**Issue by dodoma** [cesanta/mjs#10]
for example, I wan't to trace messages on js side.
How can I import printf into mjs, or, any other solution to pass variable number of arguments to c code?

**Comment by cpq** [comment]
there is no generic mechanism.

i think it is possible to FFI printf by specifying exact args you plan to pass,
e.g. `let f = ffi('int printf(char *, int , int)');  f("hi %d %d", 1, 2)`
