### ISSUE TITLE
RTLD_DEFAULT not NULL on osx

### ISSUE THREAD

**Issue by dodoma** [cesanta/mjs#11]
Just a remind, mjs ffi dlsym can't resolve funciton on mac osx.
After modify these lines in mjs/ffi.c , turns ok.

```c
#ifndef RTLD_DEFAULT
#if defined(__APPLE__)
#define RTLD_DEFAULT ((void *) -2)
#else
#define RTLD_DEFAULT NULL
#endif
#endif
```

**Comment by cpq** [comment]
does adding `-D_DARWIN_C_SOURCE` to the compilation also work?

**Comment by cpq** [comment]
@dimonomid please integrate

**Comment by dodoma** [comment]
not use -D_DARWIN_C_SOURCE yet, I'll try later.
