### ISSUE TITLE
Is it safe to turn MJS_STRING_LITERAL_MAX_LEN from 128 to 1048576 on non_embemd sys?

### ISSUE THREAD

**Issue by dodoma** [cesanta/mjs#15]
I use mjs on linux x86 64. My appilication has 1M max size string. Seems works fine after enlarge this macro. Is there any other limits on mjs for larger memory system? e.g. object prop key size, array size,  js source file size...

**Comment by cpq** [comment]
mjs core has been changed recently, i think the macro is still there but not used, there should not be limits.
