### ISSUE TITLE
2.19.0 : nothing changed?

### ISSUE THREAD

**Issue by avindra** [cesanta/mjs#157]
Per:

https://github.com/cesanta/mjs/compare/2.18.0...2.19.0

>  0 files changed

**Comment by avindra** [comment]
Nvm, I see what happened. The mongoose OS was updated, but there were 0 actual changes in `mjs`.

https://github.com/cesanta/mongoose-os/releases

**Comment by rojer** [comment]
correct. mjs repo is automatically tagged on mos release.
