### ISSUE TITLE
Can I extend mjs through mjs_op_getprop() ?

### ISSUE THREAD

**Issue by dodoma** [cesanta/mjs#16]
Say I need to pop out an item from an array, Since there is no prototypes for Array, I couldn't use array.prototype.pop() to do this. 

I notice that there is a function mjs_op_getprop() nearly to it. So, Can I write my own `pop` properity for array val?  This function is used to get valriable(push an val to &vm->dstack), not for just modify Array. I couldn't make sure is it properly?

BTW, I use array[array.length] = newitem to performe array.push(newitem),  It should be more user friendly if i extended the later way.

**Comment by cpq** [comment]
could you elaborate more on what are you trying to do on a higher level, please?

**Comment by dodoma** [comment]
I want to append an item into an array, and, pop it out later. 
This array contains some sorted, dynamic stock price information.

**Comment by cpq** [comment]
Isn't this sufficient?

https://github.com/cesanta/mjs/blob/2565635a6bef5a9d884373e2b79186ec62f2cc35/mjs.h#L244-L264

**Comment by dodoma** [comment]
Sorry for fix my last reply as following:

    I want to INSERT item into an array(at ARBITRARY position), and, pop it (or them) out later.
    This array contains some sorted, dynamic stock price information.

I tried the mjs.h offered `array related functions`, There should be two more functions to satisfy my need:

```c
mjs_array_insert(struct mjs *mjs, mjs_val_t arr, unsigned long index, mjs_val_t v);
mjs_array_del/remove(struct mjs *mjs, mjs_val_t arr, unsigned long index, unsigned long count);
```

With these functions and FFI, everything related to `array` will be ok.

**Comment by cpq** [comment]
```
let a = [1,2,3];
a[1] = 7;
JSON.stringify(a);'
```

You can insert into list. In JS, or in C via `mjs_set`

**Comment by dodoma** [comment]
maliang@bogon ~/code/mjs/mjs$ ./build/mjs -e 'let a = [1,2,3]; a[1] = 8; JSON.stringify(a)'
    [1,8,3]

I need result to be [1, 8,2,3].

`a[1] = 8;` is a array item replacement operation, not insert.
and, I need some way to delete items from array.

**Comment by cpq** [comment]
ok, you want splice, basically.

**Comment by dodoma** [comment]
en, Yes :)

**Comment by dimonomid** [comment]
`Array.prototype.splice()` is implemented in https://github.com/cesanta/mjs/commit/a15a10a5716228eb427da12bdc85843f268287d8 , closing this issue. Thanks for the feedback!
