### ISSUE TITLE
Assertion failed: (top >= 4 && (top % 4) == 0), function mjs_get_this_for_js_call

### ISSUE THREAD

**Issue by dodoma** [cesanta/mjs#17]
New mjs code, under osx, This is my test.js

```js
let o = {
    s: '',
    x: function(str) {
        this.s = str;
        print(this.s);
    },
};

o.x('hello mjs');
```

maliang@bogon ~/code/mjs/mjs$ ./build/mjs tests/y.js 
Assertion failed: (top >= 4 && (top % 4) == 0), function mjs_get_this_for_js_call, file src/mjs_exec.c, line 39.
Abort trap: 6

**Comment by cpq** [comment]
@dimonomid Dima please take this on
