### ISSUE TITLE
slice() throws MJS exec error: type error

### ISSUE THREAD

**Issue by aifer2007** [cesanta/mjs#19]
let s = "hello";
print(s); // => hello
print(s.length); // =>5
let b = s.slice(1,3); // => mgos_app_init        MJS exec error: type error
print(b); // => nothing output

**Comment by dimonomid** [comment]
There's no `"string".slice` yet, but yeah, we'll implement it soon.

**Comment by aifer2007** [comment]
Great! 
Thanks.
