### ISSUE TITLE
i compile mjs by arm-none-eabi-gcc,the code is very large

### ISSUE THREAD

**Issue by fkeujjpdc** [cesanta/mjs#21]
i put mjs.h and mjs.c into a empty project ,define MARCO  `#define CS_PLATFORM CS_P_STM32` in mjs.h.
then compile the project by arm-none-eabi-gcc,the code is very large.
```
'Invoking: Cross ARM GNU Print Size'
arm-none-eabi-size --format=berkeley "test.elf"
   text	   data	    bss	    dec	    hex	filename
 110796	   2772	    356	 113924	  1bd04	test.elf
Finished building: test.siz
```

the compile command is
` arm-none-eabi-gcc -mcpu=cortex-m3 -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections --specs=nosys.specs  -g3 -T "D:\workspace\test\START\stm32_flash.ld" -Xlinker --gc-sections -Wl,-Map,"test.map" -o "test.elf"  ./mjs/mjs.o  ./USER/io.o ./USER/main.o ./USER/uart.o  ./START/startup/startup_stm32f10x_md.o  ./START/system_stm32f10x.o  ./LIB/stm32f10x_gpio.o ./LIB/stm32f10x_rcc.o ./LIB/stm32f10x_tim.o ./LIB/stm32f10x_usart.o  ./CMSIS/core_cm3.o   `

**Comment by cpq** [comment]
That's the size of the whole firmware?
I don't see mjs.o size if your breakdown.

**Comment by fkeujjpdc** [comment]
i use the -Os flags:
this is my mjs.o size:
D:\workspace\test\Release\mjs>arm-none-eabi-size --format=berkeley "mjs.o"
   text    data     bss     dec     hex filename
  41928     136       5   42069    a455 mjs.o

the other module size is very small:
   text    data     bss     dec     hex filename
    650       0       0     650     28a stm32f10x_gpio.o
    836      20       0     856     358 stm32f10x_rcc.o
   3202       0       0    3202     c82 stm32f10x_tim.o
    924       0       0     924     39c stm32f10x_usart.o
arm-none-eabi-size: subdir.mk: File format not recognized
