### ISSUE TITLE
ffi_exports.c errors

### ISSUE THREAD

**Issue by aifer2007** [cesanta/mjs#28]
Today, when I build my mos project, I get much more ffi_exports.c erros, like this:

/app/build/gen/ffi_exports.c:146:6: error: conflicting types for 'mgos_conf_value_type'
 int  mgos_conf_value_type(void *);
      ^
/app/build/gen/ffi_exports.c:145:6: note: previous declaration of 'mgos_conf_value_type' was here
 void mgos_conf_value_type(void);

The mos project can be built some days ago.
I have updated the mos tool.

**Comment by aifer2007** [comment]
I have the ffi_symbols: in my mos.yml file.
All the ffi function in ffi_symbols list has a ffi_exports.c erros.
ffi_symbols is outdate?

**Comment by aifer2007** [comment]
yes, ffi_symbols is the reason.

**Comment by dimonomid** [comment]
ffi_exports used to contain dummy signatures like `void symbol_name(void)`, but now it contains signatures as they are given to the `ffi("..")` function (slightly preprocessed), so I think this issue should be resolved now. Feel free to reopen if it's not. Thanks for reporting!

**Comment by christianmue1980a** [comment]
I think I observed a very similar issue and described it here. Do you have an idea? https://github.com/cesanta/mongoose-os/issues/414
