### ISSUE TITLE
condition express parse bug

### ISSUE THREAD

**Issue by dodoma** [cesanta/mjs#29]
On conditional express, such as `if (expa && expb)`, if expa is false, expb should not be excuted.

for example:

```
maliang@bogon ~/code/mjs/mjs$ ./build/mjs -e "let a = 1, b = 2; if (a > 1 && (b = b+1) > 2) print(a); print(b)"
3 
undefined
```

`b` should not add 1

**Comment by dimonomid** [comment]
Yeah thanks for reporting, short-circuit evaluation was not supported indeed. Now it is (since https://github.com/cesanta/mjs/commit/2ac4ac9273345ddfbeefda1194f0e81a25e8abc6)
