### ISSUE TITLE
Does mJs support UART on ESP8266/ESP32?

### ISSUE THREAD

**Issue by aifer2007** [cesanta/mjs#3]
Does mJs support UART on ESP8266/ESP32?

If it does, How many UART ports can be used on the same ESP32?

**Comment by pirj** [comment]
How does this relate to mjs itself? mjs [provides FFI](https://github.com/cesanta/mjs#cc-interoperability), and the rest is board dependent:

    let f = ffi('int gpio_write(int, int)');  
    f(2, 1);

**Comment by pirj** [comment]
You might be interesed in [this example](https://github.com/cesanta/mongoose-os/blob/master/fw/examples/mjs_hello/fs/init.js).

**Comment by cpq** [comment]
thanks @pirj

**Comment by cpq** [comment]
@aifer2007 not  made api_uart.js yet, you can do it yourself for the time being.

Sources are at https://github.com/cesanta/mongoose-os/blob/master/fw/src/mgos_uart.h
Functions 

```
size_t mgos_uart_write(int uart_no, const void *buf, size_t len);
void mgos_uart_set_write_enabled(int uart_no, bool enabled);
void mgos_uart_flush(int uart_no);

```

Reading from the UART
