### ISSUE TITLE
build

### ISSUE THREAD

**Issue by lemonhall** [cesanta/mjs#32]
```
lemonhall@HalldeMacBook-Pro:~/Downloads/mjs/mjs$ make
Makefile:87: ../common.mk: No such file or directory
make: *** No rule to make target `../common.mk'.  Stop.
lemonhall@HalldeMacBook-Pro:~/Downloads/mjs/mjs$
```

**Comment by lemonhall** [comment]
missing some file?? common.mk??

**Comment by rwhitworth** [comment]
Also seeing this on Debian.

**Comment by rwhitworth** [comment]
Header files are also missing.  This project isn't buildable in its current state.

**Comment by dodoma** [comment]
Header files missing is imported by commit 
```
308c23a7 (Dmitry Frank 2017-05-04 17:55:52 +0100  9) #include "common/mg_str.h"
```
Seems it should be fixed soon. Currently you can check out to previous commit
```
git checkout 8fe46f1
```

This works fine.

**Comment by dodoma** [comment]
BTW, @lemonhall , 
```
echo "CLANG = gcc" > common.mk
```
on the mjs/ top directory. will  build success.

**Comment by rwhitworth** [comment]
@dodoma Thank you for the suggestions!  They produce a working build.

**Comment by dimonomid** [comment]
Thanks for reporting that, fixed.
