### ISSUE TITLE
Add API for SPI

### ISSUE THREAD

**Issue by applecrusher** [cesanta/mjs#34]
Now that SPI support has been added to Mongoose OS. Would it be possible to add the API to mjs. Thanks!

**Comment by sbeattie** [comment]
+1 Would love to try this out in Javascript too.

**Comment by dimonomid** [comment]
ETA: end of this week.

**Comment by dimonomid** [comment]
Done, see the JavaScript API reference here: https://mongoose-os.com/docs/libraries/hardware/spi.html#load

Available in latest version only so far, will be integrated in the upcoming release 1.12.

If you're on release (which is a good thing), you can either switch to latest version temporary (`mos update latest`), or just use latest versions of libs `spi` and `mjs` in your `mos.yml`, like that:

```
  - origin: https://github.com/mongoose-os-libs/spi
    version: latest
  - origin: https://github.com/mongoose-os-libs/mjs
    version: latest
```
