### ISSUE TITLE
"no userdata arg" problem

### ISSUE THREAD

**Issue by sqvarek** [cesanta/mjs#38]
Hello! I'm trying to bind this c function:

```
void sc_register_callback(void (*_callback)(char *)){
}
```

with mjs like so:

`ffi('void sc_register_callback(void (*)(char *))')
`

but mjs keeps asking about userdata arg:

MJS error: failed to exec file "api_websocket.js": bad ffi signature: "void sc_register_callback(void (*)(char *))": bad ffi signature: "void (*)(char *)": no userdata arg

**Comment by cpq** [comment]
Your registering functions needs both callback and a user data pointer that gets passed to the callback.
If you don't have any, make one.
