### ISSUE TITLE
Support require

### ISSUE THREAD

**Issue by anaptfox** [cesanta/mjs#41]
Hello!

My experience with Mongoose OS has been great! I'm currently writing an article and I had a thought. 

For onboarding of other JS users, it may be helpful to support `require` as well as `load`. Both could just reference the same function like so:

https://github.com/cesanta/mjs/blob/49cb62520964a03a1d1153be7c232ef9f43e76bd/mjs/src/mjs_builtin.c#L130

**Comment by cpq** [comment]
Simpy aliasing to `load` won't work, cause people will expect module exports to work within the loaded module.
