### ISSUE TITLE
Cool feature Proxy supports

### ISSUE THREAD

**Issue by tuoxie007** [cesanta/mjs#42]
Hey guys!

I was working on an opensource project running on iOS. I found `mjs` is my best choice as an embedded js engine although if there is a `Proxy` class like [this](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Proxy) or `method_missing` in ruby like [this](https://ruby-doc.org/core-2.1.0/BasicObject.html).

It will make `mjs` more flexible. What are you thinking?

**Comment by cpq** [comment]
The idea sounds OK
However proxy API is just too much bloat for mjs

Could you suggest the API that is lean and functional at the same time?

**Comment by cpq** [comment]
No feedback, closing
