### ISSUE TITLE
include in esp32 firmware

### ISSUE THREAD

**Issue by garfy0886** [cesanta/mjs#48]
hello, i would like to integrate mjs into my firmware but i can not understand how to do it. I tried to include the sources but I can not compile. thank you

**Comment by cpq** [comment]
Here is an example https://github.com/mongoose-os-libs/mjs

What project you're working on - is it personal or commercial?

**Comment by garfy0886** [comment]
for now this part is being tested but if everything works it should become commercial .. why?

**Comment by cpq** [comment]
For commercial clients, we provide commercial support, so if you're interested, https://mongoose-os.com/contact.html

Did you manage to build mJS for your ESP32?
Did you consider https://mongoose-os.com/ where mJS is already integrated ?

**Comment by garfy0886** [comment]
Sorry for the delay for the reply, I have not yet managed to build mJS for my ESP32. I don't understand how to include the library in my project. can you help me?
