### ISSUE TITLE
Build error due to Docker Images

### ISSUE THREAD

**Issue by kazzkiq** [cesanta/mjs#60]
When running `make`, it seems there is a try to download some Docker images, but their URL gives "connection refused" error.

The URLs are:
- docker.cesanta.com/gcc
- docker.cesanta.com/clang

The connection refusal leads to this error then trying to run `make`:

```
docker: Error response from daemon: pull access denied for docker.cesanta.com/clang, repository does not exist or may require 'docker login'.
See 'docker run --help'.
make: *** [build/mjs] Error 125
```

**Comment by dimonomid** [comment]
Thanks for reporting, should be fixed now.
