### ISSUE TITLE
mJS FFI not working (ESP8266)

### ISSUE THREAD

**Issue by vinogradov** [cesanta/mjs#7]
Example from the [documentation](https://github.com/cesanta/mjs/blob/master/README.md):
```javascript
let printf = ffi('int printf(char *, int, char *)');
printf('Hi %d %s\n', 123, 'foo');
```
Result: `MJS callback error: failed to call FFI signature "int printf(char *, int, char *)": cannot resolve function � : failed to call FFI signature "int printf(char *, int, char *)": cannot resolve function m : failed to call FFI signature "int printf(char *, int, char *)": cannot resolve function } : failed to call FFI signature "int printf(char *, int, char *)": cannot resolve function � 
`
![image](https://cloud.githubusercontent.com/assets/439939/24083330/8ce282c0-0cee-11e7-8cef-c73ed0712e51.png)

**Comment by cpq** [comment]
yes, printf example is really bad.

I've just changed it to something more stable and correct, `floor()`.

**Comment by vinogradov** [comment]
Thanks for the replay.
Since it's not possible to use `printf` (and it seems `sprintf` too) could you recommend how to convert numbers to strings or concatenate numbers with strings in mJS?

**Comment by cpq** [comment]
use JSON.parse/stringify - the "ultimate convertor".

for example, stringify and concatenate two things of any type:

let s = JSON.stringify(my_obj) + JSON.stringify(12345);

**Comment by vinogradov** [comment]
Thanks!
