### ISSUE TITLE
Cross compile MJS to MIPS platform

### ISSUE THREAD

**Issue by techparva** [cesanta/mjs#79]
I am working on a project on OpenWRT where I would like to make MJS work on MIPS platform. What steps will be required to make it work on OpenWRT toolchain?

**Comment by dimonomid** [comment]
There should be no need for anything MIPS-specific.

As to OpenWRT, I'm not personally familiar with it, but quick googling reveals that it doesn't have any compiler by default, so there probably won't be anything OpenWRT-specific either. Say, if you build it with GCC, my expectation would be that it will "just work". Let us know if you have any issues with it.
