### ISSUE TITLE
Passing a global object to a load call inside a function does not update the global object

### ISSUE THREAD

**Issue by lukeb-uk** [cesanta/mjs#86]
Assume I have a file called`module.js` that I want to load and it contains the following:
```
let test = true;
```

I then have a file`index.js` which contains the following code:
```
let obj = {};

load('module.js', obj);

print('****************');
for (let key in obj) {
    print(key);
}
print('****************');
```

When I run this, I get exactly what I expect:
```
**************** 
test 
**************** 
```

I then change the code so that the`load` call is inside a function, like so:
```
function test() {
    let obj = {};

    load('module.js', obj);
    
    print('****************');
    for (let key in obj) {
        print(key);
    }
    print('****************');
}

test();

```

When I run this, the object doesn't get updated and therefore I get no keys printed:
 
```
**************** 
****************
```

The expected outcome is that it updates the object, the same as outside of a function call.

Extra information: If I do not pass it an object as the second parameter and let it use the current global scope, it works correctly and updates the current global scope.

**Comment by dimonomid** [comment]
Thanks for reporting! Fixed in our private repo, will be published here after some time.
