### ISSUE TITLE
How to iterate over an object?

### ISSUE THREAD

**Issue by dodoma** [cesanta/mjs#9]
Can't find the js example for interate over array or object, how to do this?

**Comment by dodoma** [comment]
```js
function(anArray) {
    for (let i = 0; i < anArray.length; i++) {
        print(anArray[i]);
    }
}
```

Can iterate over an array, But over an object still not find.

**Comment by cpq** [comment]
Not possible now - the readme states `No for..in`. 

Is that something critical for you? Could you elaborate on your project please?

**Comment by dodoma** [comment]
See it. Not very critical, but may more convinionce for me.

I have two sets of stock orders(may be 40 or more), I need to iterate each one set, and find matches in another set(through id key).
Can be done use two big array, but when thy are object, will be more convenionce.

**Comment by cpq** [comment]
`for .. in` will be done, ETA - next week

**Comment by dodoma** [comment]
that is great!

**Comment by cpq** [comment]
`for..in` implemented.
