### ISSUE TITLE
Make syntax more similar to other JS implementation

### ISSUE THREAD

**Issue by stokito** [cesanta/mjs#90]
I'm new to the mjs and also I'm not a JS expert but what confused me is that mjs has some builtin functions in global scope like `print`, `load` while in other JS implementation those functions are nested into objects. So while the whole JS is OOP language the functions aren't methods which looks as design problem. Also this can violate a core mjs principle "Any valid mJS code is a valid ES6 code".

`print`  - is analogue to `console.log()` or to `process.stdout.write()` in NodeJS
`die(mesage)` - looks like `process.stderr.write()` and then `process.exit()`  in NodeJS
See https://nodejs.org/api/process.html#process_process for details but maybe later ES standard has some alternatives.

`load('file.js', obj)` - as I know, ES6/2015 provides a standard way to do that with `import` like:
```javascript
import * as data from './example.json';
const word = data.name;
console.log(word); // output 'testing'
```

`chr(n)` - looks like can be replaced with `String.fromCharCode(10)`

**Comment by cpq** [comment]
mJS goal is: with a MINIMUM resource usage, provide scripting on embedded platform.

Nesting print / die is easy,
but the rest would add a lot of unnecessary junk into the engine - so no.
resource usage takes priority over familiarity / conformance.
Need bells & whistles - go for something else.
